import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
  },

  header: {
    height: 90,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "flex-start",
  },

  footer: {
    height: 65,
  },

  viewButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 15,
  },
  tituloheader: {
    justifyContent: "space-evenly",
    alignItems: "flex-end",
    backgroundColor: "white",
    flexDirection: "row",
    width: "100%",
    height: "12%",
  },
  txttituloheader: {
    color: "black",
    textAlign: "center",
    justifyContent: "center",
    fontFamily: "Pacifico-Regular",
    fontSize: 30,
  },
  btnVoltarlondres: {
    backgroundColor: "#326e6c",
    width: 40,
    height: 40,
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  bodylondres: {
    backgroundColor: "#FFF",
    justifyContent: "center",
    borderRadius: 30,
    width: "100%",
    height: "30%",
    marginTop: "10%",
    padding: 5,
    shadowColor: "#326e6c",
    shadowOffset: { width: -1, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 5,
  },
  imagelondreshotel: {
    height: 100,
    width: 100,
    borderRadius: 20,
    top: 30,
  },
  titulohotellondres: {
    justifyContent: "center",
    alignItems: "center",
    top: -80,
    marginLeft: 110,
    fontFamily: "CormorantGaramond-Light",
    fontSize: 20,
    top: -75,
  },
  descriçãohotel: {
    justifyContent: "center",
    alignItems: "center",
    top: -50,
    marginLeft: 110,
    fontFamily: "CormorantGaramond-Light",
    fontSize: 15,
  },
  avaliaçãohotel: {
    height: 20,
    width: 80,
    marginLeft: 110,
    top: -70,
  },
  metodopagamento: {
    height: "50%",
    width: "100%",
    backgroundColor: "#FFF",
    justifyContent: "center",
    borderRadius: 30,
    marginTop: "30%",
    padding: 5,
    shadowColor: "#326e6c",
    shadowOffset: { width: -1, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 5,
  },
  caixadetexto: {
    backgroundColor: "#FFF",
    justifyContent: "center",
    borderRadius: 30,
    width: "100%%",
    height: "50%",
    padding: 20,
    marginTop: 20,
  },
  txtcaixadetexto: {
    marginTop: 100,
    borderRadius: 10,
    padding: 10,
    borderColor: "#DCDCDC",
    borderWidth: 1,
    height: "180%",
    width: "40%",
  },
  btnagendar: {
    justifyContent: "center",
    top: "25%",
    backgroundColor: "#326e6c",
    width: "20%",
    height: "10%",
    borderRadius: 7,
    marginLeft: "40%",
  },
  txtmetodo: {
    color: "black",
    alignItems: "flex-start",
    fontFamily: "CormorantGaramond-Light",
    fontSize: 30,
  },
  txtagendar: {
    textAlign: "center",
  },
  footer2: {
    alignItems: "center",
    justifyContent: "center",
    height: "100", // Define a altura do componente Footer
    backgroundColor: "#54b53f", // Define a cor de fundo
  },
});
