import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF",
  },

  header: {
    height: 90,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "flex-start",
  },

  footer: {
    height: 65,
  },

  viewButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 15,
  },
  tituloheader: {
    justifyContent: "space-evenly",
    alignItems: "flex-end",
    backgroundColor: "white",
    flexDirection: "row",
    width: "100%",
    height: "12%",
  },
  txttituloheader: {
    color: "black",
    textAlign: "center",
    justifyContent: "center",
    fontFamily: "Pacifico-Regular",
    fontSize: 30,
  },
  btnVoltarlondres: {
    backgroundColor: "#326e6c",
    width: "10%",
    height: "45%",
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  bodylondres: {
    backgroundColor: "#FFF",
    justifyContent: "center",
    borderRadius: 30,
    width: "95%",
    height: "45%",
    padding: 5,
    shadowColor: "#326e6c",
    shadowOffset: { width: -1, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 5,
    margin: 15,
  },
  imagelondreshotel: {
    height: "100%",
    width: "100%",
    borderRadius: 20,
  },
  titulohotellondres: {
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "CormorantGaramond-Light",
    fontSize: 20,
  },
  descriçãohotel: {
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "CormorantGaramond-Light",
    fontSize: 15,
  },
  avaliaçãohotel: {
    height: "90%",
    width: "30%",
  },
  metodopagamento: {
    height: "60%",
    width: "100%",
    backgroundColor: "#FFF",
    justifyContent: "center",
    borderRadius: 30,
    shadowColor: "#326e6c",
    shadowOffset: { width: -1, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 7,
    elevation: 5,
  },
  caixadetexto: {
    backgroundColor: "#FFF",
    justifyContent: "center",
    borderRadius: 30,
    width: "100%%",
    height: "60%",
    padding: 20,
  },
  txtcaixadetexto: {
    borderRadius: 10,
    padding: 10,
    borderColor: "#DCDCDC",
    borderWidth: 1,
    height: 80,
    width: "40%",
    margin: 15,
  },
  btnagendar: {
    justifyContent: "center",
    backgroundColor: "#326e6c",
    width: "30%",
    height: "100%",
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
  },
  txtmetodo: {
    color: "black",
    fontFamily: "CormorantGaramond-Light",
    fontSize: 30,
  },
  txtagendar: {
    textAlign: "center",
    fontFamily: "CormorantGaramond-Light",
    fontSize: 20,
  },
  footer2: {
    alignItems: "flex-start",
    justifyContent: "center",
    height: "15%", // Define a altura do componente Footer
    backgroundColor: "#FFF",
    borderRadius: 30,
    shadowColor: "#326e6c",
    shadowOffset: { width: -1, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 7,
    elevation: 5,
  },
  footer3: {
    alignItems: "center",
    justifyContent: "center",
    height: "60%", // Define a altura do componente Footer

    borderRadius: 20,
    width: "100%",
    flexDirection: "row",
    backgroundColor: "purple",
  },
  txtfooter: {
    fontFamily: "CormorantGaramond-Light",
    fontSize: 25,
    textAlign: "right",
  },
  txtfooter2: {
    fontFamily: "CormorantGaramond-Light",
    fontSize: 15,
  },
  botãoconfirm: {
    backgroundColor: "black",
    height: "100%",
    width: "45%",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    margin: 20,
  },
  confirm: {
    color: "white",
    fontFamily: "CormorantGaramond-Light",
    fontSize: 20,
  },
});
